name: Deploy
on:
  release:
    types: [published]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github:
    name: GitHub Milestones
    permissions:
      issues: write # Required for write access to milestones
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-milestones.yml@cc47e37177c694e00b901a5dc89fda5644bc550f # 2.9.1
    with:
      version: ${{ github.event.release.tag_name }}
